[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./builds/uniswap/"},
    { access = "read", path = "./test/the-rewarder/dvt-distribution.json"},
    { access = "read", path = "./test/the-rewarder/weth-distribution.json"},
    { access = "read", path = "./test/withdrawal/withdrawals.json"}
]
ignored_warnings_from = [
    "src/wallet-mining/TransparentProxy.sol",
    "lib/openzeppelin-contracts/contracts/proxy/Proxy.sol",
    "src/curvy-puppet/ICryptoSwapPool.sol"
]
bytecode_hash = "none"
optimizer = true
optimizer_runs = 200
[fmt]
line_length = 200
tab_width = 4
bracket_spacing=false
int_types = "long"
func_attrs_with_params_multiline = false
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"
single_line_statement_blocks = 'preserve'
variable_override_spacing = true
wrap_comments = false
ignore = []

